name: Frontend - linting

on:
  push:
    branches:
      - main
      - 'feature/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15.5'
          check-latest: true

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: bahmutov/npm-install@v1

      - name: Run frontend lint JS
        run: yarn lint:js

      - name: Run frontend lint CSS
        run: yarn lint:css
