# Custom SCSS-lint styles
#
# Less permissive rules to check during development
#
# Running this will trigger a lot of issues due to 'custom' CSS style, but
# these won't be fixed.
#
# However, it's useful to run this to spot other issues...

linters:

  # allow PostCSS colour variables
  ColorVariable:
    enabled: false

  # stop complaining about using // everywhere
  Comment:
    enabled: false

  # indentation widths, allow custom indentation
  Indentation:
    allow_non_nested_indentation: true
    width: 4

  # force leading zeros
  LeadingZero:
    style: include_zero

  # allow custom property ordering
  PropertySortOrder:
    enabled: false

  # allow PostCSS naming conventions
  SelectorFormat:
    enabled: false

  # force double quotes around strings
  StringQuotes:
    style: double_quotes
