# Jekyll settings
source: src
destination: public
includes_dir: _components

# Site settings
permalink: /:categories/:title/

# custom data - site details
sitehost: https://f90.co.uk
sitetitle: f90 // Brighton-based freelance developer
sitedescription: Online portfolio for f90 // freelance developer based in Brighton, UK
sitehandle: orangespaceman

quiet:    false
verbose:  false

liquid:
  error_mode: warn

# defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"

  - scope:
      path: "_posts/portfolio"
    values:
      layout: "portfolio-detail"
      category: "portfolio"

  - scope:
      path: "_posts/labs"
    values:
      layout: "labs-detail"
      category: "labs"
