# Site settings
source: src

# Global config settings
destination: build

# Build settings
permalink: /:categories/:title/

# defaults
defaults:
    - scope:
        path: ""
      values:
        layout: "master"

    - scope:
        path: "portfolio"
      values:
        layout: "portfolio-detail"
        category: "portfolio"

    - scope:
        path: "labs"
      values:
        layout: "labs-detail"
        category: "labs"
