# Jekyll settings
source: src
destination: public
includes_dir: _components

# Site settings
permalink: /:categories/:title/

# custom data - site details
sitehost: https://petegoodman.com
sitetitle: Pete Goodman - Brighton-based Web Developer
sitedescription: Online portfolio for Pete Goodman, freelance web developer and teacher based in Brighton, UK
sitehandle: thegingerbloke

# defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"

  - scope:
      path: "_posts/portfolio"
    values:
      layout: "portfolio-detail"
      category: "portfolio"

  - scope:
      path: "_posts/labs"
    values:
      layout: "labs-detail"
      category: "labs"
